language: 
  - python
before-install:
  - pip install -r requirements.txt  #flake8 inside

  - pip install black
  - pip install coverage
  - pip install coveralls
script:
  - black --check .
  - flake8 --max-line-length=120
after_success:
  - coveralls