language: 
  - python
before-install:
  - pip install -r requirements.txt  #flake8 inside
  - pip install
  - pip install black
  - pip install coverage
  - pip install coveralls
script:
  - black --check .

after_success:
  - coveralls